[2024-08-31T23:24:53.835+0000] {processor.py:156} INFO - Started process (PID=102) to work on /opt/airflow/dags/news_dag.py
[2024-08-31T23:24:53.837+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/news_dag.py for tasks to queue
[2024-08-31T23:24:53.840+0000] {logging_mixin.py:149} INFO - [2024-08-31T23:24:53.840+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/news_dag.py
[2024-08-31T23:24:53.902+0000] {logging_mixin.py:149} INFO - [2024-08-31T23:24:53.886+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/news_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/news_dag.py", line 10, in <module>
    from pipelines.aws_s3_pipeline import upload_s3_pipeline
ModuleNotFoundError: No module named 'pipelines'
[2024-08-31T23:24:53.904+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/news_dag.py
[2024-08-31T23:24:53.944+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/news_dag.py took 0.121 seconds
[2024-08-31T23:25:24.122+0000] {processor.py:156} INFO - Started process (PID=110) to work on /opt/airflow/dags/news_dag.py
[2024-08-31T23:25:24.124+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/news_dag.py for tasks to queue
[2024-08-31T23:25:24.133+0000] {logging_mixin.py:149} INFO - [2024-08-31T23:25:24.133+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/news_dag.py
[2024-08-31T23:25:24.184+0000] {logging_mixin.py:149} INFO - [2024-08-31T23:25:24.175+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/news_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/news_dag.py", line 10, in <module>
    from pipelines.aws_s3_pipeline import upload_s3_pipeline
ModuleNotFoundError: No module named 'pipelines'
[2024-08-31T23:25:24.186+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/news_dag.py
[2024-08-31T23:25:24.210+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/news_dag.py took 0.091 seconds
[2024-08-31T23:25:54.563+0000] {processor.py:156} INFO - Started process (PID=118) to work on /opt/airflow/dags/news_dag.py
[2024-08-31T23:25:54.565+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/news_dag.py for tasks to queue
[2024-08-31T23:25:54.566+0000] {logging_mixin.py:149} INFO - [2024-08-31T23:25:54.566+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/news_dag.py
[2024-08-31T23:25:54.603+0000] {logging_mixin.py:149} INFO - [2024-08-31T23:25:54.599+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/news_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/news_dag.py", line 10, in <module>
    from pipelines.aws_s3_pipeline import upload_s3_pipeline
ModuleNotFoundError: No module named 'pipelines'
[2024-08-31T23:25:54.605+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/news_dag.py
[2024-08-31T23:25:54.633+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/news_dag.py took 0.072 seconds
[2024-08-31T23:26:24.879+0000] {processor.py:156} INFO - Started process (PID=126) to work on /opt/airflow/dags/news_dag.py
[2024-08-31T23:26:24.881+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/news_dag.py for tasks to queue
[2024-08-31T23:26:24.882+0000] {logging_mixin.py:149} INFO - [2024-08-31T23:26:24.882+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/news_dag.py
[2024-08-31T23:26:24.941+0000] {logging_mixin.py:149} INFO - [2024-08-31T23:26:24.926+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/news_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/news_dag.py", line 10, in <module>
    from pipelines.aws_s3_pipeline import upload_s3_pipeline
ModuleNotFoundError: No module named 'pipelines'
[2024-08-31T23:26:24.946+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/news_dag.py
[2024-08-31T23:26:24.975+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/news_dag.py took 0.099 seconds
[2024-08-31T23:26:55.203+0000] {processor.py:156} INFO - Started process (PID=134) to work on /opt/airflow/dags/news_dag.py
[2024-08-31T23:26:55.206+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/news_dag.py for tasks to queue
[2024-08-31T23:26:55.207+0000] {logging_mixin.py:149} INFO - [2024-08-31T23:26:55.207+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/news_dag.py
[2024-08-31T23:26:55.261+0000] {logging_mixin.py:149} INFO - [2024-08-31T23:26:55.253+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/news_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/news_dag.py", line 10, in <module>
    from pipelines.aws_s3_pipeline import upload_s3_pipeline
ModuleNotFoundError: No module named 'pipelines'
[2024-08-31T23:26:55.265+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/news_dag.py
[2024-08-31T23:26:55.290+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/news_dag.py took 0.091 seconds
[2024-08-31T23:27:25.561+0000] {processor.py:156} INFO - Started process (PID=142) to work on /opt/airflow/dags/news_dag.py
[2024-08-31T23:27:25.563+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/news_dag.py for tasks to queue
[2024-08-31T23:27:25.565+0000] {logging_mixin.py:149} INFO - [2024-08-31T23:27:25.565+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/news_dag.py
[2024-08-31T23:27:25.634+0000] {logging_mixin.py:149} INFO - [2024-08-31T23:27:25.619+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/news_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/news_dag.py", line 10, in <module>
    from pipelines.aws_s3_pipeline import upload_s3_pipeline
ModuleNotFoundError: No module named 'pipelines'
[2024-08-31T23:27:25.638+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/news_dag.py
[2024-08-31T23:27:25.665+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/news_dag.py took 0.108 seconds
[2024-08-31T23:27:53.909+0000] {processor.py:156} INFO - Started process (PID=150) to work on /opt/airflow/dags/news_dag.py
[2024-08-31T23:27:53.910+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/news_dag.py for tasks to queue
[2024-08-31T23:27:53.912+0000] {logging_mixin.py:149} INFO - [2024-08-31T23:27:53.911+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/news_dag.py
[2024-08-31T23:27:53.969+0000] {logging_mixin.py:149} INFO - [2024-08-31T23:27:53.962+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/news_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/news_dag.py", line 10, in <module>
    from pipelines.aws_s3_pipeline import upload_s3_pipeline
ModuleNotFoundError: No module named 'pipelines'
[2024-08-31T23:27:53.971+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/news_dag.py
[2024-08-31T23:27:53.991+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/news_dag.py took 0.086 seconds
[2024-08-31T23:28:24.265+0000] {processor.py:156} INFO - Started process (PID=158) to work on /opt/airflow/dags/news_dag.py
[2024-08-31T23:28:24.267+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/news_dag.py for tasks to queue
[2024-08-31T23:28:24.268+0000] {logging_mixin.py:149} INFO - [2024-08-31T23:28:24.268+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/news_dag.py
[2024-08-31T23:28:24.315+0000] {logging_mixin.py:149} INFO - [2024-08-31T23:28:24.303+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/news_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/news_dag.py", line 10, in <module>
    from pipelines.aws_s3_pipeline import upload_s3_pipeline
ModuleNotFoundError: No module named 'pipelines'
[2024-08-31T23:28:24.319+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/news_dag.py
[2024-08-31T23:28:24.345+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/news_dag.py took 0.085 seconds
[2024-08-31T23:28:54.665+0000] {processor.py:156} INFO - Started process (PID=166) to work on /opt/airflow/dags/news_dag.py
[2024-08-31T23:28:54.667+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/news_dag.py for tasks to queue
[2024-08-31T23:28:54.669+0000] {logging_mixin.py:149} INFO - [2024-08-31T23:28:54.668+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/news_dag.py
[2024-08-31T23:28:54.722+0000] {logging_mixin.py:149} INFO - [2024-08-31T23:28:54.713+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/news_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/news_dag.py", line 10, in <module>
    from pipelines.aws_s3_pipeline import upload_s3_pipeline
ModuleNotFoundError: No module named 'pipelines'
[2024-08-31T23:28:54.723+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/news_dag.py
[2024-08-31T23:28:54.761+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/news_dag.py took 0.100 seconds
[2024-08-31T23:29:24.969+0000] {processor.py:156} INFO - Started process (PID=174) to work on /opt/airflow/dags/news_dag.py
[2024-08-31T23:29:24.971+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/news_dag.py for tasks to queue
[2024-08-31T23:29:24.972+0000] {logging_mixin.py:149} INFO - [2024-08-31T23:29:24.972+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/news_dag.py
[2024-08-31T23:29:25.040+0000] {logging_mixin.py:149} INFO - [2024-08-31T23:29:25.026+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/news_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/news_dag.py", line 10, in <module>
    from pipelines.aws_s3_pipeline import upload_s3_pipeline
ModuleNotFoundError: No module named 'pipelines'
[2024-08-31T23:29:25.044+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/news_dag.py
[2024-08-31T23:29:25.076+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/news_dag.py took 0.112 seconds
[2024-08-31T23:29:55.394+0000] {processor.py:156} INFO - Started process (PID=182) to work on /opt/airflow/dags/news_dag.py
[2024-08-31T23:29:55.396+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/news_dag.py for tasks to queue
[2024-08-31T23:29:55.398+0000] {logging_mixin.py:149} INFO - [2024-08-31T23:29:55.398+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/news_dag.py
[2024-08-31T23:29:55.456+0000] {logging_mixin.py:149} INFO - [2024-08-31T23:29:55.444+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/news_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/news_dag.py", line 10, in <module>
    from pipelines.aws_s3_pipeline import upload_s3_pipeline
ModuleNotFoundError: No module named 'pipelines'
[2024-08-31T23:29:55.460+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/news_dag.py
[2024-08-31T23:29:55.481+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/news_dag.py took 0.092 seconds
[2024-08-31T23:30:25.684+0000] {processor.py:156} INFO - Started process (PID=190) to work on /opt/airflow/dags/news_dag.py
[2024-08-31T23:30:25.685+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/news_dag.py for tasks to queue
[2024-08-31T23:30:25.687+0000] {logging_mixin.py:149} INFO - [2024-08-31T23:30:25.687+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/news_dag.py
[2024-08-31T23:30:25.739+0000] {logging_mixin.py:149} INFO - [2024-08-31T23:30:25.726+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/news_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/news_dag.py", line 10, in <module>
    from pipelines.aws_s3_pipeline import upload_s3_pipeline
ModuleNotFoundError: No module named 'pipelines'
[2024-08-31T23:30:25.742+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/news_dag.py
[2024-08-31T23:30:25.764+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/news_dag.py took 0.083 seconds
[2024-08-31T23:30:56.079+0000] {processor.py:156} INFO - Started process (PID=198) to work on /opt/airflow/dags/news_dag.py
[2024-08-31T23:30:56.081+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/news_dag.py for tasks to queue
[2024-08-31T23:30:56.084+0000] {logging_mixin.py:149} INFO - [2024-08-31T23:30:56.084+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/news_dag.py
[2024-08-31T23:30:56.139+0000] {logging_mixin.py:149} INFO - [2024-08-31T23:30:56.126+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/news_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/news_dag.py", line 10, in <module>
    from pipelines.aws_s3_pipeline import upload_s3_pipeline
ModuleNotFoundError: No module named 'pipelines'
[2024-08-31T23:30:56.144+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/news_dag.py
[2024-08-31T23:30:56.171+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/news_dag.py took 0.095 seconds
[2024-08-31T23:31:26.361+0000] {processor.py:156} INFO - Started process (PID=206) to work on /opt/airflow/dags/news_dag.py
[2024-08-31T23:31:26.363+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/news_dag.py for tasks to queue
[2024-08-31T23:31:26.364+0000] {logging_mixin.py:149} INFO - [2024-08-31T23:31:26.364+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/news_dag.py
[2024-08-31T23:31:26.397+0000] {logging_mixin.py:149} INFO - [2024-08-31T23:31:26.391+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/news_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/news_dag.py", line 10, in <module>
    from pipelines.aws_s3_pipeline import upload_s3_pipeline
ModuleNotFoundError: No module named 'pipelines'
[2024-08-31T23:31:26.400+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/news_dag.py
[2024-08-31T23:31:26.427+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/news_dag.py took 0.070 seconds
[2024-08-31T23:31:40.551+0000] {processor.py:156} INFO - Started process (PID=207) to work on /opt/airflow/dags/news_dag.py
[2024-08-31T23:31:40.552+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/news_dag.py for tasks to queue
[2024-08-31T23:31:40.554+0000] {logging_mixin.py:149} INFO - [2024-08-31T23:31:40.553+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/news_dag.py
[2024-08-31T23:31:40.611+0000] {logging_mixin.py:149} INFO - [2024-08-31T23:31:40.607+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/news_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/news_dag.py", line 10, in <module>
    from pipelines.aws_s3_pipeline import upload_s3_pipeline
ModuleNotFoundError: No module named 'pipelines'
[2024-08-31T23:31:40.613+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/news_dag.py
[2024-08-31T23:31:40.632+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/news_dag.py took 0.084 seconds
[2024-08-31T23:32:10.923+0000] {processor.py:156} INFO - Started process (PID=215) to work on /opt/airflow/dags/news_dag.py
[2024-08-31T23:32:10.924+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/news_dag.py for tasks to queue
[2024-08-31T23:32:10.925+0000] {logging_mixin.py:149} INFO - [2024-08-31T23:32:10.925+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/news_dag.py
[2024-08-31T23:32:10.968+0000] {logging_mixin.py:149} INFO - [2024-08-31T23:32:10.958+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/news_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/news_dag.py", line 10, in <module>
    from pipelines.aws_s3_pipeline import upload_s3_pipeline
ModuleNotFoundError: No module named 'pipelines'
[2024-08-31T23:32:10.971+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/news_dag.py
[2024-08-31T23:32:10.992+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/news_dag.py took 0.072 seconds
[2024-08-31T23:32:41.237+0000] {processor.py:156} INFO - Started process (PID=223) to work on /opt/airflow/dags/news_dag.py
[2024-08-31T23:32:41.241+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/news_dag.py for tasks to queue
[2024-08-31T23:32:41.242+0000] {logging_mixin.py:149} INFO - [2024-08-31T23:32:41.242+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/news_dag.py
[2024-08-31T23:32:41.274+0000] {logging_mixin.py:149} INFO - [2024-08-31T23:32:41.270+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/news_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/news_dag.py", line 10, in <module>
    from pipelines.aws_s3_pipeline import upload_s3_pipeline
ModuleNotFoundError: No module named 'pipelines'
[2024-08-31T23:32:41.275+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/news_dag.py
[2024-08-31T23:32:41.295+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/news_dag.py took 0.060 seconds
[2024-08-31T23:33:11.564+0000] {processor.py:156} INFO - Started process (PID=231) to work on /opt/airflow/dags/news_dag.py
[2024-08-31T23:33:11.565+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/news_dag.py for tasks to queue
[2024-08-31T23:33:11.566+0000] {logging_mixin.py:149} INFO - [2024-08-31T23:33:11.566+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/news_dag.py
[2024-08-31T23:33:11.605+0000] {logging_mixin.py:149} INFO - [2024-08-31T23:33:11.596+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/news_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/news_dag.py", line 10, in <module>
    from pipelines.aws_s3_pipeline import upload_s3_pipeline
ModuleNotFoundError: No module named 'pipelines'
[2024-08-31T23:33:11.607+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/news_dag.py
[2024-08-31T23:33:11.627+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/news_dag.py took 0.066 seconds
[2024-08-31T23:33:41.903+0000] {processor.py:156} INFO - Started process (PID=239) to work on /opt/airflow/dags/news_dag.py
[2024-08-31T23:33:41.905+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/news_dag.py for tasks to queue
[2024-08-31T23:33:41.906+0000] {logging_mixin.py:149} INFO - [2024-08-31T23:33:41.906+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/news_dag.py
[2024-08-31T23:33:41.944+0000] {logging_mixin.py:149} INFO - [2024-08-31T23:33:41.937+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/news_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/news_dag.py", line 10, in <module>
    from pipelines.aws_s3_pipeline import upload_s3_pipeline
ModuleNotFoundError: No module named 'pipelines'
[2024-08-31T23:33:41.947+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/news_dag.py
[2024-08-31T23:33:41.967+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/news_dag.py took 0.066 seconds
[2024-08-31T23:34:12.184+0000] {processor.py:156} INFO - Started process (PID=247) to work on /opt/airflow/dags/news_dag.py
[2024-08-31T23:34:12.186+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/news_dag.py for tasks to queue
[2024-08-31T23:34:12.187+0000] {logging_mixin.py:149} INFO - [2024-08-31T23:34:12.187+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/news_dag.py
[2024-08-31T23:34:12.251+0000] {logging_mixin.py:149} INFO - [2024-08-31T23:34:12.236+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/news_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/news_dag.py", line 10, in <module>
    from pipelines.aws_s3_pipeline import upload_s3_pipeline
ModuleNotFoundError: No module named 'pipelines'
[2024-08-31T23:34:12.255+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/news_dag.py
[2024-08-31T23:34:12.290+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/news_dag.py took 0.109 seconds
[2024-08-31T23:34:42.503+0000] {processor.py:156} INFO - Started process (PID=255) to work on /opt/airflow/dags/news_dag.py
[2024-08-31T23:34:42.504+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/news_dag.py for tasks to queue
[2024-08-31T23:34:42.505+0000] {logging_mixin.py:149} INFO - [2024-08-31T23:34:42.505+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/news_dag.py
[2024-08-31T23:34:42.568+0000] {logging_mixin.py:149} INFO - [2024-08-31T23:34:42.561+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/news_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/news_dag.py", line 10, in <module>
    from pipelines.aws_s3_pipeline import upload_s3_pipeline
ModuleNotFoundError: No module named 'pipelines'
[2024-08-31T23:34:42.573+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/news_dag.py
[2024-08-31T23:34:42.630+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/news_dag.py took 0.131 seconds
[2024-08-31T23:35:22.734+0000] {processor.py:156} INFO - Started process (PID=263) to work on /opt/airflow/dags/news_dag.py
[2024-08-31T23:35:22.736+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/news_dag.py for tasks to queue
[2024-08-31T23:35:22.737+0000] {logging_mixin.py:149} INFO - [2024-08-31T23:35:22.737+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/news_dag.py
[2024-08-31T23:35:22.788+0000] {logging_mixin.py:149} INFO - [2024-08-31T23:35:22.777+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/news_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/news_dag.py", line 10, in <module>
    from pipelines.aws_s3_pipeline import upload_s3_pipeline
ModuleNotFoundError: No module named 'pipelines'
[2024-08-31T23:35:22.792+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/news_dag.py
[2024-08-31T23:35:22.824+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/news_dag.py took 0.093 seconds
[2024-08-31T23:35:53.044+0000] {processor.py:156} INFO - Started process (PID=271) to work on /opt/airflow/dags/news_dag.py
[2024-08-31T23:35:53.045+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/news_dag.py for tasks to queue
[2024-08-31T23:35:53.046+0000] {logging_mixin.py:149} INFO - [2024-08-31T23:35:53.046+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/news_dag.py
[2024-08-31T23:35:53.090+0000] {logging_mixin.py:149} INFO - [2024-08-31T23:35:53.081+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/news_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/news_dag.py", line 10, in <module>
    from pipelines.aws_s3_pipeline import upload_s3_pipeline
ModuleNotFoundError: No module named 'pipelines'
[2024-08-31T23:35:53.093+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/news_dag.py
[2024-08-31T23:35:53.115+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/news_dag.py took 0.074 seconds
[2024-08-31T23:36:23.407+0000] {processor.py:156} INFO - Started process (PID=279) to work on /opt/airflow/dags/news_dag.py
[2024-08-31T23:36:23.409+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/news_dag.py for tasks to queue
[2024-08-31T23:36:23.411+0000] {logging_mixin.py:149} INFO - [2024-08-31T23:36:23.410+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/news_dag.py
[2024-08-31T23:36:23.457+0000] {logging_mixin.py:149} INFO - [2024-08-31T23:36:23.446+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/news_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/news_dag.py", line 10, in <module>
    from pipelines.aws_s3_pipeline import upload_s3_pipeline
ModuleNotFoundError: No module named 'pipelines'
[2024-08-31T23:36:23.461+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/news_dag.py
[2024-08-31T23:36:23.500+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/news_dag.py took 0.098 seconds
[2024-08-31T23:36:53.643+0000] {processor.py:156} INFO - Started process (PID=287) to work on /opt/airflow/dags/news_dag.py
[2024-08-31T23:36:53.644+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/news_dag.py for tasks to queue
[2024-08-31T23:36:53.646+0000] {logging_mixin.py:149} INFO - [2024-08-31T23:36:53.646+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/news_dag.py
[2024-08-31T23:36:53.679+0000] {logging_mixin.py:149} INFO - [2024-08-31T23:36:53.673+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/news_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/news_dag.py", line 10, in <module>
    from pipelines.aws_s3_pipeline import upload_s3_pipeline
ModuleNotFoundError: No module named 'pipelines'
[2024-08-31T23:36:53.681+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/news_dag.py
[2024-08-31T23:36:53.707+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/news_dag.py took 0.068 seconds
[2024-08-31T23:37:23.879+0000] {processor.py:156} INFO - Started process (PID=295) to work on /opt/airflow/dags/news_dag.py
[2024-08-31T23:37:23.880+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/news_dag.py for tasks to queue
[2024-08-31T23:37:23.881+0000] {logging_mixin.py:149} INFO - [2024-08-31T23:37:23.881+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/news_dag.py
[2024-08-31T23:37:23.941+0000] {logging_mixin.py:149} INFO - [2024-08-31T23:37:23.931+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/news_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/news_dag.py", line 10, in <module>
    from pipelines.aws_s3_pipeline import upload_s3_pipeline
ModuleNotFoundError: No module named 'pipelines'
[2024-08-31T23:37:23.943+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/news_dag.py
[2024-08-31T23:37:23.966+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/news_dag.py took 0.091 seconds
[2024-08-31T23:37:54.150+0000] {processor.py:156} INFO - Started process (PID=303) to work on /opt/airflow/dags/news_dag.py
[2024-08-31T23:37:54.152+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/news_dag.py for tasks to queue
[2024-08-31T23:37:54.153+0000] {logging_mixin.py:149} INFO - [2024-08-31T23:37:54.153+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/news_dag.py
[2024-08-31T23:37:54.189+0000] {logging_mixin.py:149} INFO - [2024-08-31T23:37:54.183+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/news_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/news_dag.py", line 10, in <module>
    from pipelines.aws_s3_pipeline import upload_s3_pipeline
ModuleNotFoundError: No module named 'pipelines'
[2024-08-31T23:37:54.191+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/news_dag.py
[2024-08-31T23:37:54.213+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/news_dag.py took 0.066 seconds
[2024-08-31T23:38:24.378+0000] {processor.py:156} INFO - Started process (PID=311) to work on /opt/airflow/dags/news_dag.py
[2024-08-31T23:38:24.379+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/news_dag.py for tasks to queue
[2024-08-31T23:38:24.380+0000] {logging_mixin.py:149} INFO - [2024-08-31T23:38:24.380+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/news_dag.py
[2024-08-31T23:38:24.406+0000] {logging_mixin.py:149} INFO - [2024-08-31T23:38:24.401+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/news_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/news_dag.py", line 10, in <module>
    from pipelines.aws_s3_pipeline import upload_s3_pipeline
ModuleNotFoundError: No module named 'pipelines'
[2024-08-31T23:38:24.408+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/news_dag.py
[2024-08-31T23:38:24.431+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/news_dag.py took 0.056 seconds
[2024-08-31T23:38:54.716+0000] {processor.py:156} INFO - Started process (PID=319) to work on /opt/airflow/dags/news_dag.py
[2024-08-31T23:38:54.719+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/news_dag.py for tasks to queue
[2024-08-31T23:38:54.721+0000] {logging_mixin.py:149} INFO - [2024-08-31T23:38:54.721+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/news_dag.py
[2024-08-31T23:38:54.777+0000] {logging_mixin.py:149} INFO - [2024-08-31T23:38:54.765+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/news_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/news_dag.py", line 10, in <module>
    from pipelines.aws_s3_pipeline import upload_s3_pipeline
ModuleNotFoundError: No module named 'pipelines'
[2024-08-31T23:38:54.781+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/news_dag.py
[2024-08-31T23:38:54.806+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/news_dag.py took 0.095 seconds
[2024-08-31T23:39:24.990+0000] {processor.py:156} INFO - Started process (PID=327) to work on /opt/airflow/dags/news_dag.py
[2024-08-31T23:39:24.992+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/news_dag.py for tasks to queue
[2024-08-31T23:39:24.994+0000] {logging_mixin.py:149} INFO - [2024-08-31T23:39:24.994+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/news_dag.py
[2024-08-31T23:39:25.065+0000] {logging_mixin.py:149} INFO - [2024-08-31T23:39:25.052+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/news_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/news_dag.py", line 10, in <module>
    from pipelines.aws_s3_pipeline import upload_s3_pipeline
ModuleNotFoundError: No module named 'pipelines'
[2024-08-31T23:39:25.068+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/news_dag.py
[2024-08-31T23:39:25.093+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/news_dag.py took 0.108 seconds
[2024-08-31T23:39:50.250+0000] {processor.py:156} INFO - Started process (PID=335) to work on /opt/airflow/dags/news_dag.py
[2024-08-31T23:39:50.252+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/news_dag.py for tasks to queue
[2024-08-31T23:39:50.253+0000] {logging_mixin.py:149} INFO - [2024-08-31T23:39:50.253+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/news_dag.py
[2024-08-31T23:39:50.355+0000] {logging_mixin.py:149} INFO - [2024-08-31T23:39:50.342+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/news_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/news_dag.py", line 10, in <module>
    from pipelines.aws_s3_pipeline import upload_s3_pipeline
ModuleNotFoundError: No module named 'pipelines'
[2024-08-31T23:39:50.358+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/news_dag.py
[2024-08-31T23:39:50.383+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/news_dag.py took 0.137 seconds
[2024-08-31T23:40:20.695+0000] {processor.py:156} INFO - Started process (PID=343) to work on /opt/airflow/dags/news_dag.py
[2024-08-31T23:40:20.696+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/news_dag.py for tasks to queue
[2024-08-31T23:40:20.697+0000] {logging_mixin.py:149} INFO - [2024-08-31T23:40:20.697+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/news_dag.py
[2024-08-31T23:40:20.729+0000] {logging_mixin.py:149} INFO - [2024-08-31T23:40:20.723+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/news_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/news_dag.py", line 10, in <module>
    from pipelines.aws_s3_pipeline import upload_s3_pipeline
ModuleNotFoundError: No module named 'pipelines'
[2024-08-31T23:40:20.731+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/news_dag.py
[2024-08-31T23:40:20.752+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/news_dag.py took 0.060 seconds
[2024-08-31T23:40:50.954+0000] {processor.py:156} INFO - Started process (PID=352) to work on /opt/airflow/dags/news_dag.py
[2024-08-31T23:40:50.956+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/news_dag.py for tasks to queue
[2024-08-31T23:40:50.957+0000] {logging_mixin.py:149} INFO - [2024-08-31T23:40:50.957+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/news_dag.py
[2024-08-31T23:40:51.001+0000] {logging_mixin.py:149} INFO - [2024-08-31T23:40:50.992+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/news_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/news_dag.py", line 10, in <module>
    from pipelines.aws_s3_pipeline import upload_s3_pipeline
ModuleNotFoundError: No module named 'pipelines'
[2024-08-31T23:40:51.005+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/news_dag.py
[2024-08-31T23:40:51.031+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/news_dag.py took 0.080 seconds
[2024-08-31T23:40:52.095+0000] {processor.py:156} INFO - Started process (PID=353) to work on /opt/airflow/dags/news_dag.py
[2024-08-31T23:40:52.097+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/news_dag.py for tasks to queue
[2024-08-31T23:40:52.099+0000] {logging_mixin.py:149} INFO - [2024-08-31T23:40:52.098+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/news_dag.py
[2024-08-31T23:40:52.171+0000] {logging_mixin.py:149} INFO - [2024-08-31T23:40:52.162+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/news_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/news_dag.py", line 10, in <module>
    from pipelines.aws_s3_pipeline import upload_s3_pipeline
ModuleNotFoundError: No module named 'pipelines'
[2024-08-31T23:40:52.174+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/news_dag.py
[2024-08-31T23:40:52.197+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/news_dag.py took 0.106 seconds
[2024-08-31T23:41:22.412+0000] {processor.py:156} INFO - Started process (PID=361) to work on /opt/airflow/dags/news_dag.py
[2024-08-31T23:41:22.413+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/news_dag.py for tasks to queue
[2024-08-31T23:41:22.414+0000] {logging_mixin.py:149} INFO - [2024-08-31T23:41:22.414+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/news_dag.py
[2024-08-31T23:41:22.442+0000] {logging_mixin.py:149} INFO - [2024-08-31T23:41:22.437+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/news_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/news_dag.py", line 10, in <module>
    from pipelines.aws_s3_pipeline import upload_s3_pipeline
ModuleNotFoundError: No module named 'pipelines'
[2024-08-31T23:41:22.445+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/news_dag.py
[2024-08-31T23:41:22.469+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/news_dag.py took 0.061 seconds
[2024-08-31T23:41:52.724+0000] {processor.py:156} INFO - Started process (PID=369) to work on /opt/airflow/dags/news_dag.py
[2024-08-31T23:41:52.726+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/news_dag.py for tasks to queue
[2024-08-31T23:41:52.728+0000] {logging_mixin.py:149} INFO - [2024-08-31T23:41:52.728+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/news_dag.py
[2024-08-31T23:41:52.794+0000] {logging_mixin.py:149} INFO - [2024-08-31T23:41:52.781+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/news_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/news_dag.py", line 10, in <module>
    from pipelines.aws_s3_pipeline import upload_s3_pipeline
ModuleNotFoundError: No module named 'pipelines'
[2024-08-31T23:41:52.798+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/news_dag.py
[2024-08-31T23:41:52.821+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/news_dag.py took 0.102 seconds
[2024-08-31T23:42:23.083+0000] {processor.py:156} INFO - Started process (PID=377) to work on /opt/airflow/dags/news_dag.py
[2024-08-31T23:42:23.085+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/news_dag.py for tasks to queue
[2024-08-31T23:42:23.087+0000] {logging_mixin.py:149} INFO - [2024-08-31T23:42:23.087+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/news_dag.py
[2024-08-31T23:42:23.152+0000] {logging_mixin.py:149} INFO - [2024-08-31T23:42:23.142+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/news_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/news_dag.py", line 10, in <module>
    from pipelines.aws_s3_pipeline import upload_s3_pipeline
ModuleNotFoundError: No module named 'pipelines'
[2024-08-31T23:42:23.155+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/news_dag.py
[2024-08-31T23:42:23.186+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/news_dag.py took 0.109 seconds
[2024-08-31T23:42:53.440+0000] {processor.py:156} INFO - Started process (PID=385) to work on /opt/airflow/dags/news_dag.py
[2024-08-31T23:42:53.442+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/news_dag.py for tasks to queue
[2024-08-31T23:42:53.443+0000] {logging_mixin.py:149} INFO - [2024-08-31T23:42:53.443+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/news_dag.py
[2024-08-31T23:42:53.485+0000] {logging_mixin.py:149} INFO - [2024-08-31T23:42:53.477+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/news_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/news_dag.py", line 10, in <module>
    from pipelines.aws_s3_pipeline import upload_s3_pipeline
ModuleNotFoundError: No module named 'pipelines'
[2024-08-31T23:42:53.488+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/news_dag.py
[2024-08-31T23:42:53.510+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/news_dag.py took 0.075 seconds
[2024-08-31T23:43:23.773+0000] {processor.py:156} INFO - Started process (PID=393) to work on /opt/airflow/dags/news_dag.py
[2024-08-31T23:43:23.774+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/news_dag.py for tasks to queue
[2024-08-31T23:43:23.776+0000] {logging_mixin.py:149} INFO - [2024-08-31T23:43:23.776+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/news_dag.py
[2024-08-31T23:43:23.817+0000] {logging_mixin.py:149} INFO - [2024-08-31T23:43:23.813+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/news_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/news_dag.py", line 10, in <module>
    from pipelines.aws_s3_pipeline import upload_s3_pipeline
ModuleNotFoundError: No module named 'pipelines'
[2024-08-31T23:43:23.820+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/news_dag.py
[2024-08-31T23:43:23.842+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/news_dag.py took 0.073 seconds
[2024-08-31T23:43:54.092+0000] {processor.py:156} INFO - Started process (PID=401) to work on /opt/airflow/dags/news_dag.py
[2024-08-31T23:43:54.094+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/news_dag.py for tasks to queue
[2024-08-31T23:43:54.095+0000] {logging_mixin.py:149} INFO - [2024-08-31T23:43:54.095+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/news_dag.py
[2024-08-31T23:43:54.133+0000] {logging_mixin.py:149} INFO - [2024-08-31T23:43:54.126+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/news_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/news_dag.py", line 10, in <module>
    from pipelines.aws_s3_pipeline import upload_s3_pipeline
ModuleNotFoundError: No module named 'pipelines'
[2024-08-31T23:43:54.135+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/news_dag.py
[2024-08-31T23:43:54.154+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/news_dag.py took 0.066 seconds
[2024-08-31T23:44:24.355+0000] {processor.py:156} INFO - Started process (PID=409) to work on /opt/airflow/dags/news_dag.py
[2024-08-31T23:44:24.356+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/news_dag.py for tasks to queue
[2024-08-31T23:44:24.357+0000] {logging_mixin.py:149} INFO - [2024-08-31T23:44:24.357+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/news_dag.py
[2024-08-31T23:44:24.379+0000] {logging_mixin.py:149} INFO - [2024-08-31T23:44:24.375+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/news_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/news_dag.py", line 10, in <module>
    from pipelines.aws_s3_pipeline import upload_s3_pipeline
ModuleNotFoundError: No module named 'pipelines'
[2024-08-31T23:44:24.381+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/news_dag.py
[2024-08-31T23:44:24.405+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/news_dag.py took 0.055 seconds
[2024-08-31T23:44:54.640+0000] {processor.py:156} INFO - Started process (PID=417) to work on /opt/airflow/dags/news_dag.py
[2024-08-31T23:44:54.641+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/news_dag.py for tasks to queue
[2024-08-31T23:44:54.642+0000] {logging_mixin.py:149} INFO - [2024-08-31T23:44:54.642+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/news_dag.py
[2024-08-31T23:44:54.661+0000] {logging_mixin.py:149} INFO - [2024-08-31T23:44:54.657+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/news_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/news_dag.py", line 10, in <module>
    from pipelines.aws_s3_pipeline import upload_s3_pipeline
ModuleNotFoundError: No module named 'pipelines'
[2024-08-31T23:44:54.663+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/news_dag.py
[2024-08-31T23:44:54.684+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/news_dag.py took 0.047 seconds
[2024-08-31T23:45:24.995+0000] {processor.py:156} INFO - Started process (PID=425) to work on /opt/airflow/dags/news_dag.py
[2024-08-31T23:45:24.997+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/news_dag.py for tasks to queue
[2024-08-31T23:45:24.998+0000] {logging_mixin.py:149} INFO - [2024-08-31T23:45:24.997+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/news_dag.py
[2024-08-31T23:45:25.027+0000] {logging_mixin.py:149} INFO - [2024-08-31T23:45:25.023+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/news_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/news_dag.py", line 10, in <module>
    from pipelines.aws_s3_pipeline import upload_s3_pipeline
ModuleNotFoundError: No module named 'pipelines'
[2024-08-31T23:45:25.029+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/news_dag.py
[2024-08-31T23:45:25.049+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/news_dag.py took 0.056 seconds
[2024-08-31T23:45:55.330+0000] {processor.py:156} INFO - Started process (PID=433) to work on /opt/airflow/dags/news_dag.py
[2024-08-31T23:45:55.332+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/news_dag.py for tasks to queue
[2024-08-31T23:45:55.333+0000] {logging_mixin.py:149} INFO - [2024-08-31T23:45:55.333+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/news_dag.py
[2024-08-31T23:45:55.390+0000] {logging_mixin.py:149} INFO - [2024-08-31T23:45:55.380+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/news_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/news_dag.py", line 10, in <module>
    from pipelines.aws_s3_pipeline import upload_s3_pipeline
ModuleNotFoundError: No module named 'pipelines'
[2024-08-31T23:45:55.392+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/news_dag.py
[2024-08-31T23:45:55.420+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/news_dag.py took 0.093 seconds
[2024-08-31T23:46:25.666+0000] {processor.py:156} INFO - Started process (PID=441) to work on /opt/airflow/dags/news_dag.py
[2024-08-31T23:46:25.668+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/news_dag.py for tasks to queue
[2024-08-31T23:46:25.669+0000] {logging_mixin.py:149} INFO - [2024-08-31T23:46:25.669+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/news_dag.py
[2024-08-31T23:46:25.726+0000] {logging_mixin.py:149} INFO - [2024-08-31T23:46:25.713+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/news_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/news_dag.py", line 10, in <module>
    from pipelines.aws_s3_pipeline import upload_s3_pipeline
ModuleNotFoundError: No module named 'pipelines'
[2024-08-31T23:46:25.731+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/news_dag.py
[2024-08-31T23:46:25.752+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/news_dag.py took 0.089 seconds
[2024-08-31T23:46:55.992+0000] {processor.py:156} INFO - Started process (PID=449) to work on /opt/airflow/dags/news_dag.py
[2024-08-31T23:46:55.993+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/news_dag.py for tasks to queue
[2024-08-31T23:46:55.995+0000] {logging_mixin.py:149} INFO - [2024-08-31T23:46:55.995+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/news_dag.py
[2024-08-31T23:46:56.056+0000] {logging_mixin.py:149} INFO - [2024-08-31T23:46:56.043+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/news_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/news_dag.py", line 10, in <module>
    from pipelines.aws_s3_pipeline import upload_s3_pipeline
ModuleNotFoundError: No module named 'pipelines'
[2024-08-31T23:46:56.060+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/news_dag.py
[2024-08-31T23:46:56.084+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/news_dag.py took 0.097 seconds
[2024-08-31T23:47:26.326+0000] {processor.py:156} INFO - Started process (PID=457) to work on /opt/airflow/dags/news_dag.py
[2024-08-31T23:47:26.328+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/news_dag.py for tasks to queue
[2024-08-31T23:47:26.329+0000] {logging_mixin.py:149} INFO - [2024-08-31T23:47:26.329+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/news_dag.py
[2024-08-31T23:47:26.379+0000] {logging_mixin.py:149} INFO - [2024-08-31T23:47:26.362+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/news_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/news_dag.py", line 10, in <module>
    from pipelines.aws_s3_pipeline import upload_s3_pipeline
ModuleNotFoundError: No module named 'pipelines'
[2024-08-31T23:47:26.381+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/news_dag.py
[2024-08-31T23:47:26.408+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/news_dag.py took 0.087 seconds
[2024-08-31T23:47:56.632+0000] {processor.py:156} INFO - Started process (PID=465) to work on /opt/airflow/dags/news_dag.py
[2024-08-31T23:47:56.634+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/news_dag.py for tasks to queue
[2024-08-31T23:47:56.635+0000] {logging_mixin.py:149} INFO - [2024-08-31T23:47:56.635+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/news_dag.py
[2024-08-31T23:47:56.671+0000] {logging_mixin.py:149} INFO - [2024-08-31T23:47:56.662+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/news_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/news_dag.py", line 10, in <module>
    from pipelines.aws_s3_pipeline import upload_s3_pipeline
ModuleNotFoundError: No module named 'pipelines'
[2024-08-31T23:47:56.675+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/news_dag.py
[2024-08-31T23:47:56.699+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/news_dag.py took 0.070 seconds
[2024-08-31T23:48:26.963+0000] {processor.py:156} INFO - Started process (PID=472) to work on /opt/airflow/dags/news_dag.py
[2024-08-31T23:48:26.965+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/news_dag.py for tasks to queue
[2024-08-31T23:48:26.965+0000] {logging_mixin.py:149} INFO - [2024-08-31T23:48:26.965+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/news_dag.py
[2024-08-31T23:48:27.011+0000] {logging_mixin.py:149} INFO - [2024-08-31T23:48:27.000+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/news_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/news_dag.py", line 10, in <module>
    from pipelines.aws_s3_pipeline import upload_s3_pipeline
ModuleNotFoundError: No module named 'pipelines'
[2024-08-31T23:48:27.015+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/news_dag.py
[2024-08-31T23:48:27.036+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/news_dag.py took 0.076 seconds
[2024-08-31T23:48:57.298+0000] {processor.py:156} INFO - Started process (PID=480) to work on /opt/airflow/dags/news_dag.py
[2024-08-31T23:48:57.299+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/news_dag.py for tasks to queue
[2024-08-31T23:48:57.301+0000] {logging_mixin.py:149} INFO - [2024-08-31T23:48:57.301+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/news_dag.py
[2024-08-31T23:48:57.354+0000] {logging_mixin.py:149} INFO - [2024-08-31T23:48:57.346+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/news_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/news_dag.py", line 10, in <module>
    from pipelines.aws_s3_pipeline import upload_s3_pipeline
ModuleNotFoundError: No module named 'pipelines'
[2024-08-31T23:48:57.356+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/news_dag.py
[2024-08-31T23:48:57.379+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/news_dag.py took 0.084 seconds
[2024-08-31T23:49:27.545+0000] {processor.py:156} INFO - Started process (PID=488) to work on /opt/airflow/dags/news_dag.py
[2024-08-31T23:49:27.546+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/news_dag.py for tasks to queue
[2024-08-31T23:49:27.548+0000] {logging_mixin.py:149} INFO - [2024-08-31T23:49:27.548+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/news_dag.py
[2024-08-31T23:49:27.592+0000] {logging_mixin.py:149} INFO - [2024-08-31T23:49:27.585+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/news_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/news_dag.py", line 10, in <module>
    from pipelines.aws_s3_pipeline import upload_s3_pipeline
ModuleNotFoundError: No module named 'pipelines'
[2024-08-31T23:49:27.594+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/news_dag.py
[2024-08-31T23:49:27.613+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/news_dag.py took 0.072 seconds
[2024-08-31T23:49:57.977+0000] {processor.py:156} INFO - Started process (PID=496) to work on /opt/airflow/dags/news_dag.py
[2024-08-31T23:49:57.979+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/news_dag.py for tasks to queue
[2024-08-31T23:49:57.981+0000] {logging_mixin.py:149} INFO - [2024-08-31T23:49:57.981+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/news_dag.py
[2024-08-31T23:49:58.045+0000] {logging_mixin.py:149} INFO - [2024-08-31T23:49:58.033+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/news_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/news_dag.py", line 10, in <module>
    from pipelines.aws_s3_pipeline import upload_s3_pipeline
ModuleNotFoundError: No module named 'pipelines'
[2024-08-31T23:49:58.049+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/news_dag.py
[2024-08-31T23:49:58.076+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/news_dag.py took 0.104 seconds
[2024-08-31T23:50:28.220+0000] {processor.py:156} INFO - Started process (PID=504) to work on /opt/airflow/dags/news_dag.py
[2024-08-31T23:50:28.221+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/news_dag.py for tasks to queue
[2024-08-31T23:50:28.224+0000] {logging_mixin.py:149} INFO - [2024-08-31T23:50:28.224+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/news_dag.py
[2024-08-31T23:50:28.256+0000] {logging_mixin.py:149} INFO - [2024-08-31T23:50:28.250+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/news_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/news_dag.py", line 10, in <module>
    from pipelines.aws_s3_pipeline import upload_s3_pipeline
ModuleNotFoundError: No module named 'pipelines'
[2024-08-31T23:50:28.258+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/news_dag.py
[2024-08-31T23:50:28.282+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/news_dag.py took 0.066 seconds
[2024-08-31T23:50:58.520+0000] {processor.py:156} INFO - Started process (PID=512) to work on /opt/airflow/dags/news_dag.py
[2024-08-31T23:50:58.522+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/news_dag.py for tasks to queue
[2024-08-31T23:50:58.523+0000] {logging_mixin.py:149} INFO - [2024-08-31T23:50:58.523+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/news_dag.py
[2024-08-31T23:50:58.586+0000] {logging_mixin.py:149} INFO - [2024-08-31T23:50:58.572+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/news_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/news_dag.py", line 10, in <module>
    from pipelines.aws_s3_pipeline import upload_s3_pipeline
ModuleNotFoundError: No module named 'pipelines'
[2024-08-31T23:50:58.590+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/news_dag.py
[2024-08-31T23:50:58.622+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/news_dag.py took 0.105 seconds
[2024-08-31T23:51:28.810+0000] {processor.py:156} INFO - Started process (PID=520) to work on /opt/airflow/dags/news_dag.py
[2024-08-31T23:51:28.812+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/news_dag.py for tasks to queue
[2024-08-31T23:51:28.813+0000] {logging_mixin.py:149} INFO - [2024-08-31T23:51:28.812+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/news_dag.py
[2024-08-31T23:51:28.850+0000] {logging_mixin.py:149} INFO - [2024-08-31T23:51:28.845+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/news_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/news_dag.py", line 10, in <module>
    from pipelines.aws_s3_pipeline import upload_s3_pipeline
ModuleNotFoundError: No module named 'pipelines'
[2024-08-31T23:51:28.852+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/news_dag.py
[2024-08-31T23:51:28.879+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/news_dag.py took 0.071 seconds
[2024-08-31T23:51:59.135+0000] {processor.py:156} INFO - Started process (PID=528) to work on /opt/airflow/dags/news_dag.py
[2024-08-31T23:51:59.136+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/news_dag.py for tasks to queue
[2024-08-31T23:51:59.137+0000] {logging_mixin.py:149} INFO - [2024-08-31T23:51:59.137+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/news_dag.py
[2024-08-31T23:51:59.161+0000] {logging_mixin.py:149} INFO - [2024-08-31T23:51:59.156+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/news_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/news_dag.py", line 10, in <module>
    from pipelines.aws_s3_pipeline import upload_s3_pipeline
ModuleNotFoundError: No module named 'pipelines'
[2024-08-31T23:51:59.163+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/news_dag.py
[2024-08-31T23:51:59.180+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/news_dag.py took 0.048 seconds
[2024-08-31T23:52:29.442+0000] {processor.py:156} INFO - Started process (PID=536) to work on /opt/airflow/dags/news_dag.py
[2024-08-31T23:52:29.443+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/news_dag.py for tasks to queue
[2024-08-31T23:52:29.444+0000] {logging_mixin.py:149} INFO - [2024-08-31T23:52:29.444+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/news_dag.py
[2024-08-31T23:52:29.487+0000] {logging_mixin.py:149} INFO - [2024-08-31T23:52:29.478+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/news_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/news_dag.py", line 10, in <module>
    from pipelines.aws_s3_pipeline import upload_s3_pipeline
ModuleNotFoundError: No module named 'pipelines'
[2024-08-31T23:52:29.490+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/news_dag.py
[2024-08-31T23:52:29.507+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/news_dag.py took 0.067 seconds
[2024-08-31T23:52:59.722+0000] {processor.py:156} INFO - Started process (PID=544) to work on /opt/airflow/dags/news_dag.py
[2024-08-31T23:52:59.723+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/news_dag.py for tasks to queue
[2024-08-31T23:52:59.724+0000] {logging_mixin.py:149} INFO - [2024-08-31T23:52:59.724+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/news_dag.py
[2024-08-31T23:52:59.773+0000] {logging_mixin.py:149} INFO - [2024-08-31T23:52:59.762+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/news_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/news_dag.py", line 10, in <module>
    from pipelines.aws_s3_pipeline import upload_s3_pipeline
ModuleNotFoundError: No module named 'pipelines'
[2024-08-31T23:52:59.777+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/news_dag.py
[2024-08-31T23:52:59.799+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/news_dag.py took 0.079 seconds
[2024-08-31T23:53:30.031+0000] {processor.py:156} INFO - Started process (PID=552) to work on /opt/airflow/dags/news_dag.py
[2024-08-31T23:53:30.032+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/news_dag.py for tasks to queue
[2024-08-31T23:53:30.034+0000] {logging_mixin.py:149} INFO - [2024-08-31T23:53:30.033+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/news_dag.py
[2024-08-31T23:53:30.070+0000] {logging_mixin.py:149} INFO - [2024-08-31T23:53:30.063+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/news_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/news_dag.py", line 10, in <module>
    from pipelines.aws_s3_pipeline import upload_s3_pipeline
ModuleNotFoundError: No module named 'pipelines'
[2024-08-31T23:53:30.073+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/news_dag.py
[2024-08-31T23:53:30.090+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/news_dag.py took 0.061 seconds
[2024-08-31T23:54:00.341+0000] {processor.py:156} INFO - Started process (PID=560) to work on /opt/airflow/dags/news_dag.py
[2024-08-31T23:54:00.343+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/news_dag.py for tasks to queue
[2024-08-31T23:54:00.344+0000] {logging_mixin.py:149} INFO - [2024-08-31T23:54:00.344+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/news_dag.py
[2024-08-31T23:54:00.381+0000] {logging_mixin.py:149} INFO - [2024-08-31T23:54:00.375+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/news_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/news_dag.py", line 10, in <module>
    from pipelines.aws_s3_pipeline import upload_s3_pipeline
ModuleNotFoundError: No module named 'pipelines'
[2024-08-31T23:54:00.383+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/news_dag.py
[2024-08-31T23:54:00.398+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/news_dag.py took 0.059 seconds
[2024-08-31T23:54:30.616+0000] {processor.py:156} INFO - Started process (PID=568) to work on /opt/airflow/dags/news_dag.py
[2024-08-31T23:54:30.617+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/news_dag.py for tasks to queue
[2024-08-31T23:54:30.618+0000] {logging_mixin.py:149} INFO - [2024-08-31T23:54:30.618+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/news_dag.py
[2024-08-31T23:54:30.652+0000] {logging_mixin.py:149} INFO - [2024-08-31T23:54:30.647+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/news_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/news_dag.py", line 10, in <module>
    from pipelines.aws_s3_pipeline import upload_s3_pipeline
ModuleNotFoundError: No module named 'pipelines'
[2024-08-31T23:54:30.655+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/news_dag.py
[2024-08-31T23:54:30.671+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/news_dag.py took 0.058 seconds
[2024-08-31T23:55:01.015+0000] {processor.py:156} INFO - Started process (PID=576) to work on /opt/airflow/dags/news_dag.py
[2024-08-31T23:55:01.016+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/news_dag.py for tasks to queue
[2024-08-31T23:55:01.017+0000] {logging_mixin.py:149} INFO - [2024-08-31T23:55:01.017+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/news_dag.py
[2024-08-31T23:55:01.049+0000] {logging_mixin.py:149} INFO - [2024-08-31T23:55:01.043+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/news_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/news_dag.py", line 10, in <module>
    from pipelines.aws_s3_pipeline import upload_s3_pipeline
ModuleNotFoundError: No module named 'pipelines'
[2024-08-31T23:55:01.051+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/news_dag.py
[2024-08-31T23:55:01.067+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/news_dag.py took 0.054 seconds
[2024-08-31T23:55:31.288+0000] {processor.py:156} INFO - Started process (PID=584) to work on /opt/airflow/dags/news_dag.py
[2024-08-31T23:55:31.289+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/news_dag.py for tasks to queue
[2024-08-31T23:55:31.290+0000] {logging_mixin.py:149} INFO - [2024-08-31T23:55:31.290+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/news_dag.py
[2024-08-31T23:55:31.329+0000] {logging_mixin.py:149} INFO - [2024-08-31T23:55:31.321+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/news_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/news_dag.py", line 10, in <module>
    from pipelines.aws_s3_pipeline import upload_s3_pipeline
ModuleNotFoundError: No module named 'pipelines'
[2024-08-31T23:55:31.332+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/news_dag.py
[2024-08-31T23:55:31.347+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/news_dag.py took 0.062 seconds
[2024-08-31T23:56:01.585+0000] {processor.py:156} INFO - Started process (PID=592) to work on /opt/airflow/dags/news_dag.py
[2024-08-31T23:56:01.586+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/news_dag.py for tasks to queue
[2024-08-31T23:56:01.587+0000] {logging_mixin.py:149} INFO - [2024-08-31T23:56:01.587+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/news_dag.py
[2024-08-31T23:56:01.624+0000] {logging_mixin.py:149} INFO - [2024-08-31T23:56:01.617+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/news_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/news_dag.py", line 10, in <module>
    from pipelines.aws_s3_pipeline import upload_s3_pipeline
ModuleNotFoundError: No module named 'pipelines'
[2024-08-31T23:56:01.627+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/news_dag.py
[2024-08-31T23:56:01.641+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/news_dag.py took 0.058 seconds
[2024-08-31T23:56:31.864+0000] {processor.py:156} INFO - Started process (PID=600) to work on /opt/airflow/dags/news_dag.py
[2024-08-31T23:56:31.866+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/news_dag.py for tasks to queue
[2024-08-31T23:56:31.867+0000] {logging_mixin.py:149} INFO - [2024-08-31T23:56:31.867+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/news_dag.py
[2024-08-31T23:56:31.905+0000] {logging_mixin.py:149} INFO - [2024-08-31T23:56:31.897+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/news_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/news_dag.py", line 10, in <module>
    from pipelines.aws_s3_pipeline import upload_s3_pipeline
ModuleNotFoundError: No module named 'pipelines'
[2024-08-31T23:56:31.908+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/news_dag.py
[2024-08-31T23:56:31.922+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/news_dag.py took 0.062 seconds
[2024-08-31T23:57:02.138+0000] {processor.py:156} INFO - Started process (PID=608) to work on /opt/airflow/dags/news_dag.py
[2024-08-31T23:57:02.139+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/news_dag.py for tasks to queue
[2024-08-31T23:57:02.140+0000] {logging_mixin.py:149} INFO - [2024-08-31T23:57:02.140+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/news_dag.py
[2024-08-31T23:57:02.162+0000] {logging_mixin.py:149} INFO - [2024-08-31T23:57:02.158+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/news_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/news_dag.py", line 10, in <module>
    from pipelines.aws_s3_pipeline import upload_s3_pipeline
ModuleNotFoundError: No module named 'pipelines'
[2024-08-31T23:57:02.163+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/news_dag.py
[2024-08-31T23:57:02.182+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/news_dag.py took 0.046 seconds
[2024-08-31T23:57:32.447+0000] {processor.py:156} INFO - Started process (PID=616) to work on /opt/airflow/dags/news_dag.py
[2024-08-31T23:57:32.448+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/news_dag.py for tasks to queue
[2024-08-31T23:57:32.449+0000] {logging_mixin.py:149} INFO - [2024-08-31T23:57:32.449+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/news_dag.py
[2024-08-31T23:57:32.486+0000] {logging_mixin.py:149} INFO - [2024-08-31T23:57:32.478+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/news_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/news_dag.py", line 10, in <module>
    from pipelines.aws_s3_pipeline import upload_s3_pipeline
ModuleNotFoundError: No module named 'pipelines'
[2024-08-31T23:57:32.489+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/news_dag.py
[2024-08-31T23:57:32.505+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/news_dag.py took 0.061 seconds
[2024-08-31T23:58:02.751+0000] {processor.py:156} INFO - Started process (PID=624) to work on /opt/airflow/dags/news_dag.py
[2024-08-31T23:58:02.752+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/news_dag.py for tasks to queue
[2024-08-31T23:58:02.753+0000] {logging_mixin.py:149} INFO - [2024-08-31T23:58:02.753+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/news_dag.py
[2024-08-31T23:58:02.791+0000] {logging_mixin.py:149} INFO - [2024-08-31T23:58:02.784+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/news_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/news_dag.py", line 10, in <module>
    from pipelines.aws_s3_pipeline import upload_s3_pipeline
ModuleNotFoundError: No module named 'pipelines'
[2024-08-31T23:58:02.794+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/news_dag.py
[2024-08-31T23:58:02.811+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/news_dag.py took 0.063 seconds
[2024-08-31T23:58:33.086+0000] {processor.py:156} INFO - Started process (PID=632) to work on /opt/airflow/dags/news_dag.py
[2024-08-31T23:58:33.087+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/news_dag.py for tasks to queue
[2024-08-31T23:58:33.088+0000] {logging_mixin.py:149} INFO - [2024-08-31T23:58:33.088+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/news_dag.py
[2024-08-31T23:58:33.141+0000] {logging_mixin.py:149} INFO - [2024-08-31T23:58:33.130+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/news_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/news_dag.py", line 10, in <module>
    from pipelines.aws_s3_pipeline import upload_s3_pipeline
ModuleNotFoundError: No module named 'pipelines'
[2024-08-31T23:58:33.145+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/news_dag.py
[2024-08-31T23:58:33.174+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/news_dag.py took 0.091 seconds
[2024-08-31T23:59:03.407+0000] {processor.py:156} INFO - Started process (PID=640) to work on /opt/airflow/dags/news_dag.py
[2024-08-31T23:59:03.409+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/news_dag.py for tasks to queue
[2024-08-31T23:59:03.410+0000] {logging_mixin.py:149} INFO - [2024-08-31T23:59:03.410+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/news_dag.py
[2024-08-31T23:59:03.467+0000] {logging_mixin.py:149} INFO - [2024-08-31T23:59:03.460+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/news_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/news_dag.py", line 10, in <module>
    from pipelines.aws_s3_pipeline import upload_s3_pipeline
ModuleNotFoundError: No module named 'pipelines'
[2024-08-31T23:59:03.469+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/news_dag.py
[2024-08-31T23:59:03.490+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/news_dag.py took 0.087 seconds
[2024-08-31T23:59:33.848+0000] {processor.py:156} INFO - Started process (PID=648) to work on /opt/airflow/dags/news_dag.py
[2024-08-31T23:59:33.850+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/news_dag.py for tasks to queue
[2024-08-31T23:59:33.851+0000] {logging_mixin.py:149} INFO - [2024-08-31T23:59:33.851+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/news_dag.py
[2024-08-31T23:59:33.910+0000] {logging_mixin.py:149} INFO - [2024-08-31T23:59:33.895+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/news_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/news_dag.py", line 10, in <module>
    from pipelines.aws_s3_pipeline import upload_s3_pipeline
ModuleNotFoundError: No module named 'pipelines'
[2024-08-31T23:59:33.915+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/news_dag.py
[2024-08-31T23:59:33.949+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/news_dag.py took 0.105 seconds
